export class CityPincodemMock {
    constructor(){
          return {
  status: true,
  "districts": [
    {
      "CircleName": "Maharashtra Circle",
      "RegionName": "Nagpur Region",
      "DivisionName": "Amaravati Division",
      "OfficeName": "Bhatkuli S.O",
      "Pincode": 444602,
      "OfficeType": "PO",
      "Delivery": "Non Delivery",
      "District": "AMRAVATI",
      "StateName": "MAHARASHTRA",
      "Latitude": 20.907,
      "Longitude": 77.6026
    },
    {
      "CircleName": "Maharashtra Circle",
      "RegionName": "Nagpur Region",
      "DivisionName": "Chandrapur Division",
      "OfficeName": "Subai B.O",
      "Pincode": 442905,
      "OfficeType": "BO",
      "Delivery": "Delivery",
      "District": "CHANDRAPUR",
      "StateName": "MAHARASHTRA",
      "Latitude": 19.5733438,
      "Longitude": 79.4422593
    },
    {
      "CircleName": "Maharashtra Circle",
      "RegionName": "Nagpur Region",
      "DivisionName": "Chandrapur Division",
      "OfficeName": "Tembhuwahi B.O",
      "Pincode": 442905,
      "OfficeType": "BO",
      "Delivery": "Delivery",
      "District": "CHANDRAPUR",
      "StateName": "MAHARASHTRA",
      "Latitude": 19.6924335,
      "Longitude": 79.3571161
    },
    {
      "CircleName": "Maharashtra Circle",
      "RegionName": "Nagpur Region",
      "DivisionName": "Chandrapur Division",
      "OfficeName": "Vihirgaon B.O",
      "Pincode": 442905,
      "OfficeType": "BO",
      "Delivery": "Delivery",
      "District": "CHANDRAPUR",
      "StateName": "MAHARASHTRA",
      "Latitude": 19.7268087,
      "Longitude": 79.453512
    },
    {
      "CircleName": "Maharashtra Circle",
      "RegionName": "Aurangabad Region",
      "DivisionName": "Osmanabad Division",
      "OfficeName": "Nilegaon B.O",
      "Pincode": 413603,
      "OfficeType": "BO",
      "Delivery": "Delivery",
      "District": "OSMANABAD",
      "StateName": "MAHARASHTRA",
      "Latitude": 18.010041,
      "Longitude": 76.0710641
    },
    {
      "CircleName": "Maharashtra Circle",
      "RegionName": "Aurangabad Region",
      "DivisionName": "Osmanabad Division",
      "OfficeName": "Omerga Chivari B.O",
      "Pincode": 413603,
      "OfficeType": "BO",
      "Delivery": "Delivery",
      "District": "OSMANABAD",
      "StateName": "MAHARASHTRA",
      "Latitude": 18.010041,
      "Longitude": 76.0710641
    },
    {
      "CircleName": "Maharashtra Circle",
      "RegionName": "Aurangabad Region",
      "DivisionName": "Osmanabad Division",
      "OfficeName": "Shahapur B.O",
      "Pincode": 413603,
      "OfficeType": "BO",
      "Delivery": "Delivery",
      "District": "OSMANABAD",
      "StateName": "MAHARASHTRA",
      "Latitude": 18.010041,
      "Longitude": 76.0710641
    },
    {
      "CircleName": "Maharashtra Circle",
      "RegionName": "Aurangabad Region",
      "DivisionName": "Osmanabad Division",
      "OfficeName": "Sukta B.O",
      "Pincode": 413504,
      "OfficeType": "BO",
      "Delivery": "Delivery",
      "District": "OSMANABAD",
      "StateName": "MAHARASHTRA",
      "Latitude": 18.4495119,
      "Longitude": 75.6758187
    },
    {
      "CircleName": "Maharashtra Circle",
      "RegionName": "Aurangabad Region",
      "DivisionName": "Osmanabad Division",
      "OfficeName": "Uloop B.O",
      "Pincode": 413504,
      "OfficeType": "BO",
      "Delivery": "Delivery",
      "District": "OSMANABAD",
      "StateName": "MAHARASHTRA",
      "Latitude": 18.4495119,
      "Longitude": 75.6758187
    },
    {
      "CircleName": "Maharashtra Circle",
      "RegionName": "Aurangabad Region",
      "DivisionName": "Osmanabad Division",
      "OfficeName": "Walwad B.O",
      "Pincode": 413504,
      "OfficeType": "BO",
      "Delivery": "Delivery",
      "District": "OSMANABAD",
      "StateName": "MAHARASHTRA",
      "Latitude": 18.4495119,
      "Longitude": 75.6758187
    },
    {
      "CircleName": "Maharashtra Circle",
      "RegionName": "Aurangabad Region",
      "DivisionName": "Osmanabad Division",
      "OfficeName": "Wanjarwadi B.O",
      "Pincode": 413504,
      "OfficeType": "BO",
      "Delivery": "Delivery",
      "District": "OSMANABAD",
      "StateName": "MAHARASHTRA",
      "Latitude": 18.4495119,
      "Longitude": 75.6758187
    },
    {
      "CircleName": "Maharashtra Circle",
      "RegionName": "Aurangabad Region",
      "DivisionName": "Osmanabad Division",
      "OfficeName": "Dhanuri B.O",
      "Pincode": 413604,
      "OfficeType": "BO",
      "Delivery": "Delivery",
      "District": "OSMANABAD",
      "StateName": "MAHARASHTRA",
      "Latitude": 17.863953,
      "Longitude": 76.478571
    },
    {
      "CircleName": "Maharashtra Circle",
      "RegionName": "Aurangabad Region",
      "DivisionName": "Osmanabad Division",
      "OfficeName": "Ekurga B.O",
      "Pincode": 413604,
      "OfficeType": "BO",
      "Delivery": "Delivery",
      "District": "OSMANABAD",
      "StateName": "MAHARASHTRA",
      "Latitude": 17.863953,
      "Longitude": 76.478571
    },
    {
      "CircleName": "Maharashtra Circle",
      "RegionName": "Aurangabad Region",
      "DivisionName": "Osmanabad Division",
      "OfficeName": "Jakekur B.O",
      "Pincode": 413604,
      "OfficeType": "BO",
      "Delivery": "Delivery",
      "District": "OSMANABAD",
      "StateName": "MAHARASHTRA",
      "Latitude": 17.863953,
      "Longitude": 76.478571
    },
    {
      "CircleName": "Maharashtra Circle",
      "RegionName": "Aurangabad Region",
      "DivisionName": "Osmanabad Division",
      "OfficeName": "Kaldeo Nimbala B.O",
      "Pincode": 413604,
      "OfficeType": "BO",
      "Delivery": "Delivery",
      "District": "OSMANABAD",
      "StateName": "MAHARASHTRA",
      "Latitude": 17.863953,
      "Longitude": 76.478571
    },
    {
      "CircleName": "Maharashtra Circle",
      "RegionName": "Pune Region",
      "DivisionName": "Satara Division",
      "OfficeName": "Ambale B.O",
      "Pincode": 415014,
      "OfficeType": "BO",
      "Delivery": "Delivery",
      "District": "SATARA",
      "StateName": "MAHARASHTRA",
      "Latitude": 17.3770329,
      "Longitude": 73.901252
    },
    {
      "CircleName": "Maharashtra Circle",
      "RegionName": "Pune Region",
      "DivisionName": "Satara Division",
      "OfficeName": "Avarde B.O",
      "Pincode": 415014,
      "OfficeType": "BO",
      "Delivery": "Delivery",
      "District": "SATARA",
      "StateName": "MAHARASHTRA",
      "Latitude": 17.3770329,
      "Longitude": 73.901252
    },
    {
      "CircleName": "Maharashtra Circle",
      "RegionName": "Pune Region",
      "DivisionName": "Satara Division",
      "OfficeName": "Bambawade B.O",
      "Pincode": 415014,
      "OfficeType": "BO",
      "Delivery": "Delivery",
      "District": "SATARA",
      "StateName": "MAHARASHTRA",
      "Latitude": 17.3770359,
      "Longitude": 73.901249
    },
    {
      "CircleName": "Maharashtra Circle",
      "RegionName": "Pune Region",
      "DivisionName": "Satara Division",
      "OfficeName": "Murud B.O",
      "Pincode": 415014,
      "OfficeType": "BO",
      "Delivery": "Delivery",
      "District": "SATARA",
      "StateName": "MAHARASHTRA",
      "Latitude": 17.5344629,
      "Longitude": 73.9069508
    },
    {
      "CircleName": "Maharashtra Circle",
      "RegionName": "Pune Region",
      "DivisionName": "Satara Division",
      "OfficeName": "Nune B.O",
      "Pincode": 415014,
      "OfficeType": "BO",
      "Delivery": "Delivery",
      "District": "SATARA",
      "StateName": "MAHARASHTRA",
      "Latitude": 17.7228153,
      "Longitude": 73.944428
    }
  ],
  message: "Districts retrieved successfully"
}
    }
  
}